// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel InsertParticle

#include "Packages/jp.nobnak.gpu_uniform_grid/ShaderLibrary/UniformGrid-hl.hlsl"
#include "Assets/Samples/ShaderLibrary/ParticleData.hlsl"

[numthreads(64,1,1)]
void InsertParticle (uint3 id : SV_DispatchThreadID) {
	if (id.x >= _ParticlePositions_Length)
		return;

	float3 pos = _ParticlePositions[id.x];
    InsertElementIdAtPosition(pos, id.x);
}
